using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerMovement : MonoBehaviour {

    public float SpeedPerSecond = 16.0f;
	
	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void FixedUpdate () {
        Vector3 desiredDirection = new Vector3();

        desiredDirection.x = Input.GetAxis("Horizontal");
        desiredDirection.z = Input.GetAxis("Vertical");

		//transform.position += desiredDirection * SpeedPerSecond * Time.fixedDeltaTime;
		desiredDirection = new Vector3(
			desiredDirection.x * SpeedPerSecond * Time.fixedDeltaTime,
			GetComponent<Rigidbody>().velocity.y,
			desiredDirection.z * SpeedPerSecond * Time.fixedDeltaTime
			);
		GetComponent<Rigidbody>().velocity = desiredDirection;
	}
}
